### ISSUE TITLE
Mario kart 8 android AKP

### ISSUE THREAD

**Issue by CaptainSeaMan360** [Cyuubi/MonoNX#6]

**Comment by FearlessTobi** [comment]
Ok.

**Comment by Yvar192** [comment]
what the fuck

**Comment by zephyren25** [comment]
Good first issue :+1:

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
No shit, Mario Kart 8 Deluxe obviously won't run... MonoNX can't even display graphics nor does it have AArch32 support (which MK8DX needs!)
