### ISSUE TITLE
Android run 60 fps,1080p dolphin.

### ISSUE THREAD

**Issue by kaguta** [Cyuubi/MonoNX#8]
my cell phone runs dolphin in 1080p with 60fps rate frame.  I think it is possible for this emulator to have good speed

**Comment by Ash1569** [comment]
@Cyuubi This needs to be closed please, Thanks :)
First of all dont create a issue just to say this...
- **_If you want to talk about this project please join the discord [here](https://discord.gg/XnbXNQM)_**

**Comment by dd01da0465b4542f8f8af4ecedc149ed** [comment]
No.
